### ISSUE TITLE
2019-05-01 Choose game folder crash

### ISSUE THREAD

**Issue by licaon-kter** [OpenMW/android-port#74]
Clean install, gave Storage perms, choose a folder with `Data Files` and a `Morrowind.ini` file copied from here http://www.fliggerty.com/phpBB3/viewtopic.php?f=63&t=4856#p83324 , the `.nomedia` file is created, but then...

```
05-02 08:58:43.313 28562 28562 E AndroidRuntime: FATAL EXCEPTION: main
05-02 08:58:43.313 28562 28562 E AndroidRuntime: Process: com.libopenmw.openmw, PID: 28562
05-02 08:58:43.313 28562 28562 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:505)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	... 1 more
05-02 08:58:43.313 28562 28562 E AndroidRuntime: Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.libopenmw.openmw/config/openmw/openmw.fallback.cfg (No such file or directory)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at java.io.FileOutputStream.open0(Native Method)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:84)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:110)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:110)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at file.GameInstaller.convertIni(GameInstaller.kt:109)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at ui.fragments.FragmentSettings.setupData(FragmentSettings.kt:92)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at ui.fragments.FragmentSettings.access$setupData(FragmentSettings.kt:41)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at ui.fragments.FragmentSettings$onCreate$3$1.onSelect(FragmentSettings.kt:72)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment$1.onClick(SecondaryChooserFragment.java:111)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at android.view.View.performClick(View.java:6617)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6594)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25906)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6723)
05-02 08:58:43.313 28562 28562 E AndroidRuntime: 	... 3 more
```  

Workaround, create folder: `/storage/emulated/0/Android/data/com.libopenmw.openmw/config/openmw/` ( eg. I've backuped a test save here; ahem https://github.com/OpenMW/android-port/issues/69 ) and now it doesn't crash....

**Comment by licaon-kter** [comment]
Appears fixed @xyzz
